import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  injectedWallet,
  rainbowWallet,
  metaMaskWallet,
  coinbaseWallet,
  walletConnectWallet,
} from "@rainbow-me/rainbowkit/wallets";
import { Chain } from "wagmi";
import { allChains } from "wagmi";
const wallets = [
  injectedWallet({ chains }),
  rainbowWallet({ chains }),
  metaMaskWallet({ chains }),
  coinbaseWallet({ chains, appName: "My App" }),
  walletConnectWallet({ chains }),
];
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Template By Tomi204</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}
