import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "@rainbow-me/rainbowkit/styles.css";
import {
  getDefaultWallets,
  RainbowKitProvider,
  darkTheme,
} from "@rainbow-me/rainbowkit";
import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { infuraProvider } from "wagmi/providers/infura";
import { publicProvider } from "wagmi/providers/public";

const { chains, provider } = configureChains(
  [
    chain.mainnet,
    chain.polygon,
    chain.goerli,
    chain.avalanche,
    chain.polygonMumbai,
  ],
  [
    infuraProvider({
      apiKey: process.env.REACT_APP_WEB3APIKEY,
      stallTimeout: 1_000,
    }),

    publicProvider(),
  ]
);
const { connectors } = getDefaultWallets({
  appName: "Web3 Ecommerce",
  chains,
});
const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Template By Tomi204</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WagmiConfig client={wagmiClient}>
          <RainbowKitProvider
            modalSize="compact"
            theme={darkTheme({
              ...darkTheme.accentColors.green,
            })}
            chains={chains}
          ></RainbowKitProvider>
        </WagmiConfig>
      </main>
    </div>
  );
}
